### ISSUE TITLE
Database Module

### ISSUE THREAD

**Issue by Maelstromeous** [Maelstrome26/PS2Alerts-WebsocketServer#19]
Need to write up the Database module. This needs to be able to execute queries on the database and return the data, alongside database connection management.

Best suggestion is to have a universal "query" function, which each time it's called opens up a separate connection and then closes it as needed. Saves us having to manually manage database connections within each module.

**Comment by Maelstromeous** [comment]
@KBraham would you say this is done now or is there further work to do?

**Comment by KBraham** [comment]
We should convert the db structure to migrations, but that possibly related to #8 . Other than that the module is ready to be used.

**Comment by Maelstromeous** [comment]
Module completed.
